--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockHorizons/InvSee
branches:
- master
projects:
  InvSee:
    path: ""
    icon: icon.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.6
        branch: pm5
...
