name: InvSee
author: BlockHorizons
main: BlockHorizons\InvSee\Loader
api: 3.9.0
version: 1.0.0

permissions:
  invsee:
    default: false
    description: "Grants access to all InvSee permissions."
    children:
      invsee.inventory:
        default: false
        description: "Grants complete access to managing another player's inventory."
        children:
          invsee.inventory.view:
            default: op
            description: "Allows viewing a player's inventory."
          invsee.inventory.modify:
            default: op
            description: "Allows modifying a player's inventory."
            children:
              invsee.inventory.modify.self:
                default: true
                description: "Allows modifying your own inventory."
      invsee.enderinventory:
        default: false
        description: "Grants complete access to managing another player's ender inventory."
        children:
          invsee.enderinventory.view:
            default: op
            description: "Allows viewing a player's ender inventory."
          invsee.enderinventory.modify:
            default: op
            description: "Allows modifying a player's ender inventory."
            children:
              invsee.enderinventory.modify.self:
                default: true
                description: "Allows modifying your own ender inventory."
